### ISSUE TITLE
/

### ISSUE THREAD

**Issue by kzunwon** [XanthanGumm/SuperSimpleMH#3]
Type 1, 2 then press ENTER:2
None
Mem::get_unit_table_address::INFO:: Unit table has been found at offset: 0x14d2da + (7)
Mem::get_expansion_address::INFO:: Expansion has been found at offset: 0x1532b6 + (3)
Mem::get_ui_address::INFO:: UI has been found at offset: 0x23db53 + (6)
Mem::get_minions_address::INFO:: Players minions has been found at offset: 0x207e86 + (3)
Mem::get_roster_address::INFO:: Roster has been found at offset: 0x1c7716 - (3)
[!] RPC server is up.
Mem::get_last_hover_address::INFO:: Last hover has been found at offset: 0x17a0e4 + (3)
MapManager::initialize::INFO:: [!] Initialize MapManager with seed: 0x364f6140, at nightmare difficulty
MapManager::update::INFO:: [!] Requesting area data for area: 6
MapManager::update::INFO:: [!] Requesting Act1 map levels grids
MapManager::update::INFO:: [!] Loading Act1 textures
MapManager::update::INFO:: [!] Finished to load Act1 map levels after: 4.121548700000858 seconds
MapManager::get_level_data::INFO:: [!] Caching area data for area: 6
MapManager::update::INFO:: [!] Loading Act1 textures
MapManager::update::INFO:: [!] Finished to load Act1 map levels after: 5.8657695000001695 seconds
MapManager::update::INFO:: [!] Requesting area data for area: 20
MapManager::get_level_data::INFO:: [!] Caching area data for area: 20
MapManager::update::INFO:: [!] Requesting area data for area: 21
MapManager::get_level_data::INFO:: [!] Caching area data for area: 21
MapManager::update::INFO:: [!] Requesting area data for area: 22
MapManager::update::INFO:: [!] Player switched from Act-18 at the middle of processing Act-19 maps
MapManager::update::INFO:: [!] Waiting for Act-19 maps requests to finish
MapManager::update::WARNING:: [!] Canceling the process of up scaling Act-19 maps
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\kzun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\kzun\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kzun\Downloads\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 32, in run
    raise e
  File "C:\Users\kzun\Downloads\SuperSimpleMH\venv\Lib\site-packages\su_core\__main__.py", line 30, in run
    canvas.event_loop()
  File "C:\Users\kzun\Downloads\SuperSimpleMH\venv\Lib\site-packages\su_core\canvas\__init__.py", line 168, in event_loop
    self._map_manager.update(area=player_area, player_pos=player.path.position)
  File "C:\Users\kzun\Downloads\SuperSimpleMH\venv\Lib\site-packages\su_core\canvas\MapManager.py", line 96, in update
    progress_max_value = 2 * len(self._acts_levels[self._game_ui.last_act]) + progress_value
                                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by XanthanGumm** [comment]
Thank you.
bug has been fixed.
